name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "Looks like this issue is not getting much attention. If you feel this deserves more attention, try contacting one of the contributors of the project."
          stale-pr-message: "This pull request does not seem to be getting much attention. If you feel this is an important change, try contacting one of the contributors of the project."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
